# super user permission
sudo: required
services:
  - docker
# 
before_install:
  - docker build -t mydemo -f Dockerfile.dev .
# run commands to test suite
script:
  # -- --coverage: to automatically exit test when test is done
  - docker run -e CI=true mydemo npm run test
  

